name: "Maven tests"

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  codeception-tests:
    name: "Java tests"
    runs-on: "ubuntu-20.04"
    continue-on-error: false
    services:
      mariadb:
        image: "mariadb:10.8"
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: root

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Build project with Maven
        run: mvn -B package --file pom.xml
        continue-on-error: true

      - name: "Upload test report"
        uses: actions/upload-artifact@v4
        with:
          path: '**/target/surefire-reports/TEST*.xml'
          if-no-files-found: error
          retention-days: 7

      - name: Fail if tests failed
        if: steps.build_project_with_maven.outcome == 'failure'
        run: exit 1
